<?php
/**
* This class is autogenerated by the Spapi class generator
* Date of generation: 2022-04-01
* Specification: https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2020-12-01.json
* Source MD5 signature: a6212e6adca331e58a6a32b214b9408d
*
*
* Selling Partner API for Catalog Items
* The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.

For more information, see the [Catalog Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-api-use-case-guide_2022-04-01.md).
*/
namespace DoubleBreak\Spapi\Api;
use DoubleBreak\Spapi\Client;

class CatalogItems extends Client {

  protected $apiVersion = '2022-04-01';

  protected $versions = [
    '2022-04-01' => '2022-04-01',
    '2020-12-01' => '2020-12-01',
    'v0' => 'v0',
  ];

  /**
  * Operation listCatalogItems
  *
  * @param array $queryParams
  *    - *marketplaceId* string - A marketplace identifier. Specifies the marketplace for which items are returned.
  *    - *query* string - Keyword(s) to use to search for items in the catalog. Example: 'harry potter books'.
  *    - *queryContextId* string - An identifier for the context within which the given search will be performed. A marketplace might provide mechanisms for constraining a search to a subset of potential items. For example, the retail marketplace allows queries to be constrained to a specific category. The QueryContextId parameter specifies such a subset. If it is omitted, the search will be performed using the default context for the marketplace, which will typically contain the largest set of items.
  *    - *sellerSKU* string - Used to identify an item in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
  *    - *uPC* string - A 12-digit bar code used for retail packaging.
  *    - *eAN* string - A European article number that uniquely identifies the catalog item, manufacturer, and its attributes.
  *    - *iSBN* string - The unique commercial book identifier used to identify books internationally.
  *    - *jAN* string - A Japanese article number that uniquely identifies the product, manufacturer, and its attributes.
  *
  */
  public function listCatalogItems($queryParams = [])
  {
    return $this->send("/catalog/v0/items", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

    /**
  * Operation listCatalogCategories
  *
  * @param array $queryParams
  *    - *marketplaceId* string - A marketplace identifier. Specifies the marketplace for the item.
  *    - *aSIN* string - The Amazon Standard Identification Number (ASIN) of the item.
  *    - *sellerSKU* string - Used to identify items in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.
  *
  */
  public function listCatalogCategories($queryParams = [])
  {
    return $this->send("/catalog/v0/categories", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation searchCatalogItems
  *
  * @param array $queryParams
  *    - *keywords* array - A comma-delimited list of words or item identifiers to search the Amazon catalog for.
  *    - *marketplaceIds* array - A comma-delimited list of Amazon marketplace identifiers for the request.
  *    - *includedData* array - A comma-delimited list of data sets to include in the response. Default: summaries.
  *    - *brandNames* array - A comma-delimited list of brand names to limit the search to.
  *    - *classificationIds* array - A comma-delimited list of classification identifiers to limit the search to.
  *    - *pageSize* integer - Number of results to be returned per page.
  *    - *pageToken* string - A token to fetch a certain page when there are multiple pages worth of results.
  *    - *keywordsLocale* string - The language the keywords are provided in. Defaults to the primary locale of the marketplace.
  *    - *locale* string - Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  *
  */
  public function searchCatalogItems($queryParams = [])
  {
    return $this->send("/catalog/{$this->apiVersion}/items", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function searchCatalogItemsAsync($queryParams = [])
  {
    return $this->sendAsync("/catalog/{$this->apiVersion}/items", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  /**
  * Operation getCatalogItem
  *
  * @param string $asin The Amazon Standard Identification Number (ASIN) of the item.
  *
  * @param array $queryParams
  *    - *marketplaceIds* array - A comma-delimited list of Amazon marketplace identifiers. Data sets in the response contain data only for the specified marketplaces.
  *    - *includedData* array - A comma-delimited list of data sets to include in the response. Default: summaries.
  *    - *locale* string - Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  *
  */
  public function getCatalogItem($asin, $queryParams = [])
  {
    return $this->send("/catalog/{$this->apiVersion}/items/{$asin}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }

  public function getCatalogItemAsync($asin, $queryParams = [])
  {
    return $this->sendAsync("/catalog/{$this->apiVersion}/items/{$asin}", [
      'method' => 'GET',
      'query' => $queryParams,
    ]);
  }
}
